### ISSUE TITLE
각자 구현을 담당할 함수를 나눠봐요

### ISSUE THREAD

**Issue by jeeyunryu** [Park-Ryu/MedicalAppointment#7]

**Comment by jeeyunryu** [comment]
**함수 목록** 
addAppointment  **진료 예약을 추가하는 함수**
readAppointment  **하나의 예약된 진료 예약을 출력해주는 함수** 
listAppointment  **예약된 진료 예약 목록을 보여주는 함수**
updateAppointment  **예약된 진료 예약 중 특정 예약을 수정해주는 함수**
deleteAppointment  **예약된 진료 예약 중 특정 예약을 삭제해주는 함수**
selectAppointment  **예약된 진료 예약 중에 수정,삭제하고 싶은 예약을 선택해주는 함수**
saveToFile  **데이터를 파일에 저장해주는 함수**
loadFile **파일에서 저장된 데이터를 읽어오는 함수**
searchPatient **예약된 환자 이름으로 예약 내역을 출력해주는 함수** 
searchByDate **특정 일자에 예약된 예약 목록을 출력해주는 함수**
searchByDepartment  **특정 진료과에 예약된 예약 목록을 출력해주는 함수**
searchByProf  **특정 교수에게 예약된 예약 목록을 출력해주는 함수**

**Comment by Wonjin-david** [comment]
CRUD+file IO 랑 나머지 4개 함수 구현하는 걸로 나누면 어떨까 하는데 괜찮으실까요??
저는 아무거나 상관 없습니다!!

혹은 CRUD가 만들어져야 구현을 제대로 시작할 수 있으니까
# add+파일save+파일load +추가함수 2개(ex. Department, Prof)
# update+delete+read+list+추가함수 2개 (ex. patient. Date)

이렇게 해도 좋을 것 같아요!!

저는 어떤 방안이더라도 괜찮고, 나눈 것 중에서 어떤 거 해도 괜찮아서 편하게 고르셔도 될 것 같아요!

**Comment by Wonjin-david** [comment]
제가 add, read는 일단 test.c에 거의 구현해놔서 따로 구현 없어도 될 듯 합니다:)

**Comment by jeeyunryu** [comment]
add+파일save+파일load +추가함수 2개(ex. Department, Prof) - 원진
update+delete+read+list+추가함수 2개 (ex. patient. Date) - 지연
그럼 이렇게 나눠요
