### ISSUE TITLE
delete 함수 요청사항

### ISSUE THREAD

**Issue by Wonjin-david** [Park-Ryu/MedicalAppointment#9]
혹시  delete 함수 구현하실 때 꼭 m[i] ==null이 되도록 구현해주시면 감사하겠습니다.

예를 들면, list함수의 for 문 안에 구현된 것처럼
m[i]==NULL이면 continue 가 되도록 구현해주시면 감사하겠습니다:)

**Comment by jeeyunryu** [comment]
네~
